MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  NUM_CLASSES: 2
  PRETRAIN_CKPT: "./pretrained_ckpt/swin_tiny_patch4_window7_224.pth"

  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 96
    DEPTHS: [2, 2, 2, 2]
    DECODER_DEPTHS: [2, 2, 2, 1]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7

DATA:
  IMAGE_SIZE: 224

TRAIN:
  BASE_LR: 0.0001
  BATCH_SIZE: 8
  NUM_EPOCHS: 100
  NUM_WORKERS: 4

AUG:
  RANDOM_FLIP: True
  RANDOM_ROTATION: True

